/* Authored homepage copy, shared by the normal site translation adapter. */
(function(root) {
  root.OverlySiteEnglish = Object.assign(root.OverlySiteEnglish || {}, {
    "أوفرلي | اكتشاف ألطف. اختيار أوضح.": "Overly | Discover thoughtfully. Choose clearly.",
    "انتقل إلى التصنيفات": "Skip to categories",
    "ابحث في المنتجات": "Search products",
    "تعرّف على أوفرلي": "Get to know Overly",
    "مساحة لاكتشاف ما يناسبك": "A little space for your next discovery",
    "أهلًا بك في أوفرلي": "Welcome to Overly",
    "كل اهتماماتك.": "All your interests.",
    "بداية واحدة.": "One place to start.",
    "نجمع لك أبواب الاكتشاف من أمازون السعودية وعلي إكسبريس. ابدأ من اهتمامك، بدل أن تبدأ من زحمة المنتجات.": "Discover your interests across Amazon Saudi Arabia and AliExpress. Start with what matters to you, not an endless wall of products.",
    "اكتشف التصنيفات": "Explore categories",
    "كل اهتمام، له باب.": "An open door for every interest.",
    "من اهتمامك إلى اختيارك": "From interest to a considered choice",
    "اكتشف بهدوء.": "Take a closer look.",
    "واختر على ذوقك.": "Find your kind of thing.",
    "ادخل التصنيف الذي يهمك لتظهر منتجاته. استعرض التفاصيل، وقارن الخيارات، أو استخدم البحث للوصول لاحتياجك.": "Open a category to see its products. Explore the details, compare your options, or search for something specific.",
    "اختر أول اهتمام": "Choose an interest",
    "على ذوقك أنت": "Your interests. Your choice.",
    "للبيت": "For your home",
    "ليومك": "For your everyday",
    "لرحلتك": "For your next trip",
    "تفاصيل أكثر. قرار أوضح.": "More detail. A clearer decision.",
    "الشراء من المصدر": "Buy directly from the store",
    "يعجبك هنا.": "Discover it here.",
    "تشتريه من المتجر.": "Buy it at the source.",
    "افتح رابط المنتج للتحقق من السعر الحالي والشحن والتوفر، ثم أكمل الشراء في المتجر نفسه. أوفرلي دليل تسوّق، وليس جهة البيع.": "Visit the product page to check the current price, shipping and availability, then buy directly from the store. Overly is a shopping guide, not the seller.",
    "ابدأ رحلة الاكتشاف": "Start exploring",
    "تكتشف في أوفرلي": "Discover on Overly",
    "القرار لك. والشراء من المتجر.": "Your choice. The store handles the purchase.",
    "خطوات استخدام أوفرلي": "How to use Overly",
    "الخطوة الأولى: اكتشف": "Step one: discover",
    "الخطوة الثانية: اختر": "Step two: choose",
    "الخطوة الثالثة: تسوّق": "Step three: shop",
    "اكتشف": "Discover",
    "اختر": "Choose",
    "تسوّق": "Shop",
    "إيقاف الحركة التلقائية": "Pause automatic slides",
    "تشغيل الحركة التلقائية": "Play automatic slides",
    "السلايد السابق": "Previous slide",
    "السلايد التالي": "Next slide",
    "١ من ٣": "1 of 3",
    "٢ من ٣": "2 of 3",
    "٣ من ٣": "3 of 3",
    "البداية من هنا": "FIND YOUR STARTING POINT",
    "وش يهمّك اليوم؟": "What speaks to you?",
    "اختر قسمًا، وشاهد منتجاته.": "Open a category to see its products.",
    "استكشف دليل التصنيفات": "Explore the category directory",
    "توضيح طريقة عمل الموقع": "How this site works",
    "ندلّك على الخيارات. والقرار لك.": "We point the way. You make the choice.",
    "قد نحصل على عمولة عند الشراء عبر روابطنا، دون تكلفة إضافية عليك. السعر والتوفر والشحن وسياسة الإرجاع يحددها المتجر.": "We may earn a commission when you shop through our links, at no extra cost to you. Prices, availability, shipping and returns are determined by the store.",
    "إفصاح العمولة": "Affiliate disclosure",
    "اكتشاف ألطف. اختيار أوضح.": "Discover thoughtfully. Choose clearly.",
    "روابط الموقع": "Site links",
    "حقوق الملكية": "Copyright",
    "الشروط والأحكام": "Terms and conditions",
    "أوفرلي (Overly) — جميع الحقوق محفوظة.": "Overly — All rights reserved."
  });
})(globalThis);
