/* Faithful translations of the existing notices; no new legal terms. */
Object.assign(globalThis.OverlySiteEnglish,{
  "أوفرلي | Overly": "Overly",
  "العودة للموقع ←": "Back to the site →",
  "الخصوصية أولًا": "Privacy first",
  "سياسة الخصوصية": "Privacy policy",
  "نوضح هنا ما يحدث لبياناتك عند استخدام أوفرلي، بلغة مباشرة ومن دون تعقيد.": "Here is a clear, straightforward explanation of what happens to your data when you use Overly.",
  "آخر تحديث: 16 أغسطس 2026": "Last updated: 16 August 2026",
  "ينطبق على موقع أوفرلي العام": "Applies to the public Overly website",
  "1. ما الذي يجمعه الموقع؟": "1. What does the site collect?",
  "لا يطلب موقع أوفرلي العام إنشاء حساب، ولا يطلب اسمك أو رقم هاتفك أو بيانات الدفع. قد تعالج خدمات الاستضافة والحماية تقنيًا عنوان الاتصال، نوع المتصفح، ووقت الطلب لتشغيل الموقع ومنع إساءة الاستخدام.": "The public Overly website does not require an account and does not ask for your name, phone number or payment details. Hosting and security services may technically process connection addresses, browser types and request times to operate the website and prevent abuse.",
  "2. البحث داخل AliExpress": "2. AliExpress search",
  "عند استخدام البحث، تُرسل كلمة البحث إلى بوابة أوفرلي الآمنة على Cloudflare. تُستخدم بصمة تقنية مختصرة لتطبيق حد الطلبات ومنع الإغراق، ولا تُعرض للزائر ولا تُستخدم لإنشاء ملف تسويقي عنه.": "When you search, your query is sent to Overly's secure gateway on Cloudflare. A short technical fingerprint is used for rate limiting and flood prevention. It is not shown to visitors or used to build a marketing profile.",
  "3. التخزين على جهازك": "3. Storage on your device",
  "قد يستخدم الموقع التخزين المحلي في متصفحك لحفظ تفضيل الوضع الداكن وبعض عناصر تجربة الاستخدام. تبقى هذه البيانات على جهازك ويمكنك حذفها من إعدادات المتصفح.": "The site may use your browser's local storage to remember your dark-mode preference and some aspects of the user experience. This data stays on your device and can be removed in your browser settings.",
  "4. الروابط الخارجية": "4. External links",
  "عند الضغط على رابط منتج ستنتقل إلى Amazon أو AliExpress أو متجر خارجي. يخضع استخدامك هناك لسياسة الخصوصية الخاصة بذلك المتجر، وقد تستخدم روابط العمولة معرّفات تقنية لاحتساب الإحالة والعمولة.": "Clicking a product link takes you to Amazon, AliExpress or another external store. Your use there is subject to that store's privacy policy. Affiliate links may use technical identifiers to attribute referrals and commissions.",
  "5. التحليلات المجمعة": "5. Aggregated analytics",
  "يسجل أوفرلي حدث مشاهدة الصفحة وحدث الضغط على المنتج لقياس أداء الموقع وتحسين المحتوى. تشمل البيانات: اليوم والوقت، نوع الحدث، معرّف المنتج وعنوانه وتصنيفه ومتجره عند الضغط، مسار الصفحة، نطاق مصدر الزيارة، الدولة التقريبية، ونوع الجهاز بصورة عامة. لا نحفظ عنوان IP، ولا الاسم أو البريد، ولا معرّفًا دائمًا للزائر، ولا ننشئ ملفًا شخصيًا لتتبعه بين المواقع.": "Overly records page views and product clicks to measure site performance and improve content. Data includes the date and time, event type, product ID, title, category and store when clicked, page path, referring domain, approximate country and general device type. We do not store IP addresses, names, email addresses or permanent visitor identifiers, and do not create personal profiles to track people across websites.",
  "6. ملفات تعريف الارتباط": "6. Cookies",
  "لا تتطلب تحليلات أوفرلي ملفات تعريف ارتباط ولا تخزن رقمًا فريدًا للزائر. قد تستخدم خدمات Cloudflare وGitHub وواجهات المتاجر ملفات تقنية ضرورية للأمان والتشغيل.": "Overly analytics do not require cookies or store a unique visitor number. Cloudflare, GitHub and store interfaces may use technical cookies necessary for security and operation.",
  "7. مشاركة البيانات": "7. Data sharing",
  "لا يبيع أوفرلي بيانات الزوار الشخصية. قد تمر البيانات التقنية الضرورية عبر مزودي التشغيل والحماية بالقدر اللازم لتقديم الموقع، أو عندما يتطلب النظام ذلك.": "Overly does not sell visitors' personal data. Necessary technical data may pass through hosting and security providers to the extent required to deliver the website, or where required by law.",
  "8. الأمان والاحتفاظ": "8. Security and retention",
  "تُحفظ مفاتيح الربط داخل GitHub Secrets وCloudflare Secrets ولا تُرسل إلى متصفح الزائر. تُخزن سجلات التحليلات المجمعة في Cloudflare D1 لمدة تصل إلى 180 يومًا ثم تُحذف تلقائيًا. نستخدم اتصالات HTTPS وقيودًا للطلبات، مع الإقرار بأنه لا توجد خدمة إلكترونية تضمن حماية مطلقة بنسبة 100٪.": "Integration keys are stored in GitHub Secrets and Cloudflare Secrets and are not sent to visitors' browsers. Aggregated analytics records are stored in Cloudflare D1 for up to 180 days, then deleted automatically. We use HTTPS and request limits, while recognising that no online service can guarantee absolute, 100% protection.",
  "9. حقوقك والتواصل": "9. Your rights and contact",
  "يمكنك مسح التخزين المحلي من متصفحك أو التوقف عن استخدام الموقع. ولأن التحليلات لا تحتوي على معرّف دائم للزائر، لا يمكن ربط سجل بعينه بشخص محدد. للاستفسار أو طلب متعلق بالخصوصية، استخدم": "You can clear local storage in your browser or stop using the site. Because analytics have no permanent visitor identifier, a particular record cannot be linked to a specific person. For privacy questions or requests, use",
  "قناة التواصل الرسمية للمشروع": "the project's official contact channel",
  "، وتجنب نشر أي بيانات حساسة داخل البلاغ العام.": ", and avoid posting sensitive data in the public report.",
  "10. تحديث السياسة": "10. Policy updates",
  "قد تُحدّث هذه السياسة عند تغير طريقة عمل الموقع أو المتطلبات النظامية. يظهر تاريخ آخر تحديث أعلى الصفحة.": "This policy may be updated when the website's operation or legal requirements change. The latest update date appears at the top of the page.",
  "هذه الصفحة بيان عام لطريقة التعامل مع البيانات، وليست بديلًا عن استشارة قانونية متخصصة عند الحاجة.": "This page is a general statement about data handling, not a substitute for specialist legal advice where needed.",
  "الخصوصية": "Privacy",
  "شروط الاستخدام": "Terms of use",
  "إفصاح العمولة": "Affiliate disclosure",
  "حقوق الملكية": "Intellectual property",
  "© 2026 أوفرلي (Overly) — جميع الحقوق محفوظة.": "© 2026 Overly — All rights reserved.",
  "استخدام واضح وعادل": "Clear and fair use",
  "باستخدامك أوفرلي فإنك توافق على الشروط التالية المتعلقة بالمحتوى والأسعار والروابط الخارجية.": "By using Overly, you agree to the following terms relating to content, prices and external links.",
  "المملكة العربية السعودية": "Kingdom of Saudi Arabia",
  "1. طبيعة الخدمة": "1. Nature of the service",
  "أوفرلي منصة لاكتشاف منتجات وعروض وروابط تسويق بالعمولة. لا يبيع أوفرلي المنتجات مباشرة، ولا يستلم المدفوعات، ولا يعد طرفًا في عقد الشراء بين المستخدم والمتجر.": "Overly is a platform for discovering products, offers and affiliate links. Overly does not sell products directly, receive payments or form part of the purchase contract between the user and the store.",
  "2. الأسعار والتوفر": "2. Prices and availability",
  "الأسعار ونسب الخصم والتوفر قد تتغير بعد آخر تحديث. السعر والشروط النهائية المعتمدة هي الظاهرة في صفحة المتجر عند إتمام الطلب. عرض منتج في أوفرلي لا يمثل ضمانًا باستمرار سعره أو توفره أو شحنه.": "Prices, discounts and availability may change after the latest update. The final applicable price and terms are those shown on the store's page when completing the order. Listing a product on Overly does not guarantee its continuing price, availability or shipping.",
  "3. بيانات المنتجات": "3. Product data",
  "نعتمد على بيانات المتاجر وواجهاتها الرسمية قدر الإمكان. قد تختلف الصور أو المواصفات أو خيارات المنتج بين المنطقة والنسخة المختارة؛ لذلك يجب مراجعة صفحة المنتج والمتجر والبائع وسياسة الإرجاع قبل الشراء.": "We rely on store data and official interfaces as far as possible. Images, specifications and product options may differ by region and selected version. Review the product, store, seller and returns policy before buying.",
  "4. روابط التسويق بالعمولة": "4. Affiliate links",
  "قد يحصل أوفرلي على عمولة عند إتمام شراء مؤهل عبر بعض الروابط، دون تكلفة إضافية مفروضة من أوفرلي عليك. التفاصيل موجودة في": "Overly may receive a commission on eligible purchases made through some links, without an additional charge imposed on you by Overly. Details are on",
  "صفحة إفصاح العمولة": "the affiliate disclosure page",
  ".": ".",
  "5. الاستخدام المقبول": "5. Acceptable use",
  "يُسمح بتصفح الموقع واستخدامه لأغراض شخصية مشروعة.": "Browsing and using the website for lawful personal purposes is permitted.",
  "يُمنع إغراق الموقع بالطلبات أو محاولة تجاوز الحماية أو الوصول إلى المفاتيح والأنظمة الإدارية.": "Flooding the site with requests, bypassing security, or attempting to access keys and administrative systems is prohibited.",
  "يُمنع نسخ قاعدة المنتجات أو التصميم أو المحتوى وإعادة نشره تجاريًا دون إذن مكتوب.": "Copying the product database, design or content and republishing it commercially without written permission is prohibited.",
  "يُمنع استخدام الموقع بطريقة تضر بالخدمة أو بحقوق المستخدمين أو الجهات الأخرى.": "Using the website in a way that harms the service, users' rights or other parties is prohibited.",
  "6. الملكية الفكرية": "6. Intellectual property",
  "تصميم أوفرلي، هويته، تنسيق المحتوى، النصوص الأصلية، والبرمجيات الخاصة به محفوظة لمالك المشروع. أسماء المنتجات والعلامات والصور التابعة للمتاجر أو المصنعين تبقى مملوكة لأصحابها.": "Overly's design, identity, content formatting, original text and proprietary software belong to the project owner. Product names, brands and images belonging to stores or manufacturers remain their owners' property.",
  "7. المسؤولية": "7. Liability",
  "يُقدّم الموقع على أساس «كما هو» في الحدود التي يسمح بها النظام. لا يتحمل أوفرلي مسؤولية جودة منتج أو شحنه أو ضمانه أو أي تغيير يجريه المتجر، وعلى المستخدم اتخاذ قرار الشراء بعد التحقق.": "The website is provided 'as is' to the extent permitted by law. Overly is not responsible for a product's quality, shipping, warranty or changes made by the store. Users should verify the information before deciding to buy.",
  "8. التعديلات": "8. Amendments",
  "يجوز تحديث هذه الشروط أو وظائف الموقع عند الحاجة. استمرار الاستخدام بعد نشر النسخة المحدثة يعني قبول الشروط المحدثة.": "These terms or website functions may be updated when needed. Continued use after an updated version is published means acceptance of the updated terms.",
  "9. التواصل": "9. Contact",
  "للبلاغات المتعلقة بالمحتوى أو الحقوق استخدم": "For content or rights reports, use",
  "، ولا تنشر بيانات شخصية أو سرية في البلاغ العام.": ", and do not post personal or confidential data in a public report.",
  "شفافية قبل النقر": "Transparency before you click",
  "إفصاح التسويق بالعمولة": "Affiliate marketing disclosure",
  "بعض روابط المنتجات في أوفرلي هي روابط عمولة، ونوضح هنا كيف تعمل وماذا تعني لك.": "Some product links on Overly are affiliate links. Here is how they work and what they mean for you.",
  "Amazon + AliExpress": "Amazon + AliExpress",
  "الإفصاح المختصر": "Short disclosure",
  "بصفتنا مشاركين في برنامج Amazon Associates، نحصل على عمولة من عمليات الشراء المؤهلة.": "As an Amazon Associate, we earn from qualifying purchases.",
  "وقد نحصل كذلك على عمولة من عمليات الشراء المؤهلة عبر روابط AliExpress أو برامج شركاء أخرى، دون أن يفرض أوفرلي عليك تكلفة إضافية.": "We may also earn commissions from qualifying purchases through AliExpress links or other partner programmes, without Overly imposing an additional charge on you.",
  "كيف تعمل الروابط؟": "How do the links work?",
  "عند الضغط على رابط يحمل معرّف أوفرلي، يستطيع المتجر معرفة أن الزيارة جاءت من موقعنا. إذا أكملت طلبًا مؤهلًا وفق شروط البرنامج، قد يدفع المتجر عمولة لأوفرلي.": "When you click a link containing Overly's identifier, the store can recognise that the visit came from our website. If you complete an eligible order under the programme's terms, the store may pay Overly a commission.",
  "هل تدفع أكثر؟": "Do you pay more?",
  "لا يضيف أوفرلي رسومًا على سعر المنتج بسبب رابط العمولة. ومع ذلك، قد تتغير الأسعار والشحن والضرائب والعروض داخل المتجر، والسعر النهائي هو ما يظهر لك قبل تأكيد الطلب.": "Overly does not add a fee to the product price because of an affiliate link. However, store prices, shipping, taxes and offers may change. The final price is the one shown before you confirm the order.",
  "استقلالية الاختيار": "Independent selection",
  "وجود عمولة لا يغيّر التزامنا بعدم اختلاق خصومات أو أسعار. ترتيب المنتجات يعتمد على البيانات المتاحة مثل الرواج والمبيعات والتقييم وملاءمة التصنيف، وقد تدخل معايير تقنية لتحسين التنوع والجودة.": "Receiving a commission does not change our commitment not to invent discounts or prices. Product order is based on available data such as popularity, sales, ratings and category relevance. Technical criteria may also improve variety and quality.",
  "Amazon": "Amazon",
  "روابط Amazon السعودية تستخدم وسم الشريك الخاص بالمشروع. بيانات السعر والتوفر الرسمية لدى Amazon هي المرجع النهائي، وقد لا تكون كل عملية شراء مؤهلة للعمولة.": "Amazon Saudi Arabia links use the project's affiliate tag. Amazon's official price and availability data are the final reference, and not every purchase may qualify for a commission.",
  "AliExpress": "AliExpress",
  "تُولّد روابط AliExpress من برنامج الشركاء الرسمي متى أعادتها الواجهة المعتمدة. احتساب العمولة يخضع لشروط AliExpress، وأهلية المنتج، وسلوك التتبع، وإتمام طلب مؤهل.": "AliExpress links are generated through its official affiliate programme when returned by the approved interface. Commission attribution is subject to AliExpress terms, product eligibility, tracking behaviour and completion of an eligible order.",
  "مسؤوليتك قبل الشراء": "Your responsibility before buying",
  "راجع وصف المنتج والبائع والشحن والضمان وسياسة الإرجاع داخل المتجر. أوفرلي يساعدك على الاكتشاف والمقارنة البصرية، لكنه ليس البائع ولا يضمن المنتج.": "Review the product description, seller, shipping, warranty and returns policy at the store. Overly helps with discovery and visual comparison, but is not the seller and does not guarantee the product.",
  "هوية ومحتوى محفوظان": "Protected identity and content",
  "حقوق الملكية الفكرية": "Intellectual property rights",
  "يوضح هذا الإشعار ملكية تصميم أوفرلي ومحتواه الأصلي، وحدود استخدام المواد المعروضة.": "This notice explains ownership of Overly's design and original content, and the limits on using the material displayed.",
  "© أوفرلي (Overly)": "© Overly",
  "1. حقوق أوفرلي": "1. Overly's rights",
  "حقوق التصميم، واجهة الاستخدام، الهوية البصرية، الشعار، ترتيب المحتوى، النصوص الأصلية، وقواعد البرمجيات التي أنشئت خصيصًا لمشروع أوفرلي محفوظة لمالك المشروع ما لم يُذكر خلاف ذلك.": "Rights to the design, interface, visual identity, logo, content arrangement, original text and software code created specifically for Overly belong to the project owner unless otherwise stated.",
  "2. الاستخدام المسموح": "2. Permitted use",
  "يجوز لك تصفح الموقع ومشاركة رابط صفحة أو منتج للاستخدام الشخصي. لا يمنحك ذلك حق نسخ قاعدة البيانات أو إعادة بناء التصميم أو نشر أجزاء جوهرية من المحتوى باسم آخر.": "You may browse the website and share a page or product link for personal use. This does not grant permission to copy the database, recreate the design or publish substantial portions of the content under another name.",
  "3. الاستخدام غير المسموح": "3. Prohibited use",
  "إعادة نشر محتوى أوفرلي أو قاعدة المنتجات بصورة آلية أو تجارية دون إذن مكتوب.": "Automated or commercial republication of Overly content or the product database without written permission.",
  "نسخ الشعار أو الهوية بطريقة توحي بوجود شراكة أو اعتماد غير موجود.": "Copying the logo or identity in a way that implies a partnership or endorsement that does not exist.",
  "إزالة إشعارات الحقوق أو الإفصاح أو نسبة المحتوى إلى جهة أخرى.": "Removing copyright notices or disclosures, or attributing the content to another party.",
  "استخدام أدوات آلية ترهق الخدمة أو تتجاوز القيود التقنية.": "Using automated tools that overload the service or bypass technical restrictions.",
  "4. علامات وصور الجهات الأخرى": "4. Third-party trademarks and images",
  "أسماء Amazon وAliExpress وأسماء المصنعين وصور المنتجات وعلاماتهم مملوكة لأصحابها. استخدامها في أوفرلي هدفه وصف المنتجات والإحالة إلى المتاجر ولا يعني امتلاكها أو وجود رعاية مباشرة ما لم يُذكر ذلك صراحة.": "Amazon, AliExpress and manufacturer names, product images and trademarks belong to their respective owners. Their use on Overly describes products and links to stores; it does not imply ownership or direct sponsorship unless explicitly stated.",
  "5. العلامة التجارية": "5. The brand",
  "«أوفرلي» و«Overly» والشعار هوية مستخدمة للمشروع. لا يعني هذا النص وحده أن العلامة مسجلة رسميًا؛ ويُستكمل التسجيل النظامي لدى الهيئة السعودية للملكية الفكرية بصورة مستقلة.": "The names 'أوفرلي' and 'Overly' and the logo form the project's identity. This statement alone does not mean the trademark is officially registered. Formal registration with the Saudi Authority for Intellectual Property is a separate process.",
  "6. بلاغات الحقوق": "6. Rights reports",
  "إذا كنت صاحب حق وترى أن مادة منشورة تنتهك حقك، أرسل": "If you own rights and believe published material infringes them, submit",
  "بلاغ حقوق ملكية": "an intellectual property report",
  "يتضمن رابط المادة ووصف الحق ووسيلة تواصل مناسبة. لا تضع مستندات هوية أو أسرارًا في البلاغ العام.": "including the material's link, a description of the right and suitable contact information. Do not include identity documents or secrets in a public report.",
  "7. الاحتفاظ بالأدلة": "7. Retaining evidence",
  "يحتفظ مالك المشروع بنسخ مؤرخة من الشعار والملفات وسجل التعديلات والنشر لإثبات التسلسل الزمني للتطوير. ويوصى باستكمال التسجيل الرسمي للعلامة والمصنفات المهمة.": "The project owner retains dated copies of the logo and files, along with modification and publication history, to establish the development timeline. Formal registration of the trademark and important works is recommended.",
  "© 2026 أوفرلي (Overly) — جميع الحقوق محفوظة. لا يوجد في هذه الصفحة ترخيص مفتوح لإعادة استخدام الكود أو الهوية.": "© 2026 Overly — All rights reserved. This page does not grant an open licence to reuse the code or identity."
});
