/* English editorial copy; meanings and seller-verification warnings preserved. */
globalThis.OverlySiteEnglish={
  "منتجات إلكترونية رائجة تشمل الشواحن والملحقات والأجهزة الذكية، مرتبة وفق بيانات الرواج المتاحة.": "Popular electronics including chargers, accessories and smart devices, ordered using available popularity data.",
  "من يبحث عن ملحقات وأجهزة عملية للاستخدام اليومي": "people looking for practical everyday accessories and devices",
  "التوافق، نوع المنفذ أو الاتصال، والضمان الذي يوضحه المتجر": "compatibility, port or connection type, and the store's stated warranty",
  "اختيارات للمنزل والمطبخ والتنظيم تساعدك على الوصول إلى المنتجات الرائجة بسرعة.": "Home, kitchen and organisation finds that help you discover popular products quickly.",
  "من يريد تحسين الاستخدام اليومي للمطبخ والمنزل": "people looking to improve everyday kitchen and home use",
  "الأبعاد، الخامة، ومتطلبات التشغيل أو التنظيف": "dimensions, materials, and operating or cleaning requirements",
  "إكسسوارات وأدوات سيارة رائجة مع روابط مباشرة للتحقق من التوافق والسعر لدى المتجر.": "Popular car accessories and tools, with direct links to check compatibility and price at the store.",
  "من يريد أدوات عملية وتنظيماً أفضل داخل السيارة": "people looking for practical tools and better in-car organisation",
  "توافق المقاس أو الموديل، طريقة التثبيت، ومصدر الطاقة": "size or model compatibility, mounting method, and power source",
  "منتجات سفر وتنظيم وراحة مختارة وفق مؤشرات الطلب المتاحة لدى المنصات.": "Travel, organisation and comfort products selected using available demand indicators.",
  "المسافرين الباحثين عن وزن أقل وتنظيم أسهل": "travellers looking for lower weight and easier organisation",
  "الأبعاد والوزن وسياسة الأمتعة وجودة الإغلاق": "dimensions, weight, baggage policies, and closure quality",
  "منتجات موضة وإكسسوارات رائجة مع تنبيه واضح لمراجعة المقاس والخامة لدى المتجر.": "Popular fashion and accessories, with a reminder to check sizing and materials at the store.",
  "من يبحث عن إكسسوارات وقطع رائجة للاستخدام اليومي": "people looking for popular everyday accessories and clothing",
  "جدول المقاسات، الخامة، وصور المشترين إن توفرت": "size charts, materials, and buyer photos where available",
  "منتجات جمال وعناية شخصية رائجة، مع ضرورة مراجعة المكونات والملاءمة الشخصية قبل الشراء.": "Popular beauty and personal-care products. Check ingredients and personal suitability before buying.",
  "من يبحث عن أدوات عناية شخصية عملية ورائجة": "people looking for practical and popular personal-care tools",
  "المكونات، تعليمات الاستخدام، والتحذيرات الموضحة لدى المتجر": "ingredients, usage instructions, and the warnings listed by the store",
  "أدوات ولياقة ومنتجات رياضية رائجة مرتبة لتسهيل المقارنة الأولية.": "Popular sports and fitness equipment organised to make initial comparisons easier.",
  "من يريد أدوات للتمارين المنزلية والنشاط اليومي": "people looking for home exercise and everyday activity equipment",
  "المقاس، تحمل الوزن، ومستوى الاستخدام المناسب": "size, weight capacity, and appropriate level of use",
  "منتجات أطفال رائجة مع تذكير بمراجعة العمر المناسب وتحذيرات السلامة لدى المتجر.": "Popular children's products, with a reminder to check age suitability and safety warnings at the store.",
  "الأسر الباحثة عن منتجات أطفال عملية": "families looking for practical children's products",
  "العمر الموصى به، المواد، وتحذيرات السلامة": "recommended age, materials, and safety warnings",
  "أدوات ومنتجات للحيوانات الأليفة مختارة وفق الرواج والبيانات المتاحة.": "Pet products and tools selected using available popularity data.",
  "مربي الحيوانات الباحثين عن أدوات يومية مفيدة": "pet owners looking for useful everyday equipment",
  "المقاس، المواد، وملاءمة المنتج لنوع الحيوان": "size, materials, and suitability for the animal",
  "أدوات وهوايات ومنتجات عملية رائجة للمشروعات المنزلية والاستخدام الشخصي.": "Popular tools and hobby products for household projects and personal use.",
  "الهواة ومن ينفذ أعمالاً منزلية بسيطة": "hobbyists and people doing simple household tasks",
  "المواصفات، الملحقات المتضمنة، ومتطلبات السلامة": "specifications, included accessories, and safety requirements",
  "بروجكترات وتلفزيونات وملحقات ترفيه منزلي رائجة مع إرشادات لفحص المواصفات قبل الشراء.": "Popular projectors, televisions and home-entertainment accessories, with guidance on checking specifications before purchase.",
  "من يبني تجربة مشاهدة أو ألعاب منزلية": "people building a home viewing or gaming setup",
  "الدقة الفعلية، السطوع، المقاس، المنافذ، والضمان": "native resolution, brightness, size, ports, and warranty",
  "منظفات وأدوات تنظيف رائجة للاستخدام المنزلي اليومي.": "Popular cleaning products and tools for everyday household use.",
  "من يبحث عن خيارات تنظيف عملية": "people looking for practical cleaning options",
  "نوع الاستخدام، الكمية، المكونات والتحذيرات": "intended use, quantity, ingredients, and warnings",
  "أدوات مطبخ وأجهزة منزلية رائجة مع بيانات المتجر الحالية.": "Popular kitchen tools and home appliances with current store data.",
  "من يريد تجهيز المطبخ بأدوات عملية": "people equipping their kitchen with practical tools",
  "السعة، الأبعاد، الجهد والضمان": "capacity, dimensions, voltage, and warranty",
  "أثاث وديكور ومنتجات تنظيم للمنزل.": "Furniture, decor and home-organisation products.",
  "من يريد تحسين مساحة المنزل": "people improving their home space",
  "الأبعاد، الخامة، اللون وطريقة التركيب": "dimensions, materials, colour, and assembly method",
  "معدات رحلات وبحر وتخييم رائجة وقابلة للشحن للسعودية حسب بيانات المتجر.": "Popular outdoor, beach and camping equipment with shipping to Saudi Arabia according to store data.",
  "محبي البر والبحر والأنشطة الخارجية": "outdoor, beach and camping enthusiasts",
  "التحمل، المقاس، الوزن ومتطلبات السلامة": "durability, size, weight, and safety requirements",
  "أدوات حدائق وزراعة وري للاستخدام المنزلي.": "Garden, planting and irrigation tools for home use.",
  "من يهتم بالحدائق والنباتات": "people interested in gardens and plants",
  "المقاس، الخامة وطريقة الاستخدام": "size, materials, and usage instructions",
  "منتجات صحة وعناية عامة مع تذكير بمراجعة تعليمات المتجر.": "General health and personal-care products, with a reminder to check store instructions.",
  "من يبحث عن أدوات عناية يومية": "people looking for everyday personal-care tools",
  "تعليمات الاستخدام، التحذيرات والملاءمة الشخصية": "usage instructions, warnings, and personal suitability",
  "منتجات بقالة ومشروبات رائجة وفق بيانات المتجر.": "Popular groceries and drinks according to store data.",
  "من يبحث عن احتياجات البقالة": "people shopping for groceries",
  "المكونات، الوزن، بلد المنشأ وتاريخ الصلاحية": "ingredients, weight, country of origin, and expiry date",
  "ألعاب ومنتجات ترفيه رائجة لمراحل عمرية مختلفة.": "Popular toys and entertainment products for different age groups.",
  "الأسر والباحثين عن ألعاب مناسبة": "families and people looking for suitable toys",
  "العمر المناسب، المواد وتحذيرات السلامة": "recommended age, materials, and safety warnings",
  "أدوات مدرسية وقرطاسية ومنتجات تعلم رائجة.": "Popular school supplies, stationery and learning products.",
  "الطلاب والأسر": "students and families",
  "العمر المناسب، المقاس، المحتويات والخامة": "recommended age, size, contents, and materials",
  "كتب وأدوات مكتبية وتنظيم مساحة العمل.": "Books, office supplies and workspace organisation.",
  "القراء والطلاب وأصحاب المكاتب": "readers, students and office users",
  "اللغة، الإصدار، المقاس والمحتويات": "language, edition, size, and contents",
  "ساعات وإكسسوارات ومجوهرات رائجة.": "Popular watches, accessories and jewellery.",
  "من يبحث عن إكسسوارات للإطلالة اليومية": "people looking for everyday accessories",
  "المقاس، الخامة، اللون والضمان": "size, materials, colour, and warranty",
  "منتجات تسوق متنوعة لا تنتمي إلى قسم متخصص.": "A range of shopping products that do not belong to a specialist category.",
  "من يستكشف المنتجات الرائجة": "people exploring popular products",
  "الوصف، المواصفات، الشحن وسياسة الإرجاع": "description, specifications, shipping, and returns policy",
  "كيف تختار شاحن GaN مناسباً دون دفع أكثر من حاجتك؟": "How to choose a GaN charger without paying for more than you need",
  "دليل عملي لفهم القدرة والمنافذ والبروتوكولات قبل شراء شاحن GaN.": "A practical guide to power, ports and protocols before buying a GaN charger.",
  "شواحن GaN أصغر عادةً من الشواحن التقليدية ذات القدرة نفسها، لكن الرقم الكبير المكتوب على المنتج لا يعني أن كل منفذ يقدّم تلك القدرة منفرداً. القرار الصحيح يبدأ من أجهزتك، لا من أعلى رقم في صفحة المنتج.": "GaN chargers are usually smaller than traditional chargers with the same power rating, but the large number on the product does not mean each port delivers that power independently. Start with your devices, not the biggest number on the listing.",
  "ابدأ بالأجهزة التي تملكها": "Start with the devices you own",
  "اكتب قدرة الشحن القصوى للهاتف واللوحي واللابتوب، ثم افحص نوع المنافذ التي تستخدمها. إذا كان اللابتوب يحتاج USB-C Power Delivery فابحث عن ذكر البروتوكول والقدرة لذلك المنفذ تحديداً، وليس القدرة الإجمالية للشاحن فقط.": "List the maximum charging power of your phone, tablet and laptop, then check the ports they use. If your laptop requires USB-C Power Delivery, look for the protocol and wattage of that specific port, not just the charger's total output.",
  "افهم توزيع الطاقة": "Understand power sharing",
  "في الشواحن متعددة المنافذ تنخفض قدرة بعض المخارج عند استخدام أكثر من جهاز. راجع جدول توزيع الطاقة في صفحة المتجر، وتأكد أن التوزيع عند توصيل أجهزتك الفعلية يظل كافياً.": "On multi-port chargers, some outputs deliver less power when several devices are connected. Check the store's power-distribution table and make sure the combination of devices you actually use still receives enough power.",
  "الكابل جزء من المعادلة": "The cable matters too",
  "قدرة الشاحن لا تصل إلى الجهاز إذا كان الكابل لا يدعمها. للشحنات الأعلى قدرة ابحث عن كابل موضح عليه دعم القدرة المناسبة وشريحة تعريف إلكترونية عند الحاجة.": "The charger's power will not reach the device if the cable does not support it. For higher-power charging, look for a cable clearly rated for the required power, with an electronic identification chip where needed.",
  "قائمة فحص سريعة": "A quick checklist",
  "تحقق من القابس المناسب للسعودية، دعم الجهد 100–240V إن كنت تسافر، عدد المنافذ، سياسة الضمان، وتقييمات الاستخدام الطويل. السعر النهائي والمواصفات المعتمدة هما ما يظهر لدى المتجر.": "Check the plug type for Saudi Arabia, 100–240V support if you travel, port count, warranty policy and long-term user reviews. The final price and confirmed specifications are those shown by the store.",
  "دليل اختيار بروجكتر للترفيه المنزلي": "A guide to choosing a home-entertainment projector",
  "ما الذي يجب فحصه في الدقة والسطوع والمسافة والمنافذ قبل شراء بروجكتر؟": "What should you check about resolution, brightness, distance and ports before buying a projector?",
  "تتشابه صور البروجكترات في المتاجر بينما تختلف التجربة الفعلية كثيراً. لا تعتمد على عبارة 4K وحدها؛ قد تعني دعم استقبال إشارة 4K بينما تكون الدقة الأصلية أقل.": "Projector images in stores can look similar while the actual experience differs greatly. Do not rely on a 4K label alone: it may mean the projector accepts a 4K signal while its native resolution is lower.",
  "الدقة الأصلية قبل التسويقية": "Native resolution before marketing claims",
  "ابحث عن Native Resolution بوضوح. الدقة الأصلية هي عدد البكسلات التي يعرضها الجهاز فعلياً، أما Supported Resolution فتعني غالباً أنه يستطيع استقبال الإشارة ثم تحويلها.": "Look for a clear Native Resolution specification. This is the number of pixels the projector actually displays. Supported Resolution usually means it can receive the signal and convert it.",
  "السطوع والبيئة": "Brightness and the room",
  "الغرفة المظلمة تحتاج سطوعاً أقل من غرفة المعيشة نهاراً. قارن أرقام ANSI Lumens حين تكون متاحة بدلاً من أرقام غير موحدة، وتذكر أن الستارة والإضاءة المحيطة تؤثران في النتيجة.": "A dark room requires less brightness than a living room during the day. Compare ANSI Lumens where available rather than non-standard figures. Curtains and ambient lighting also affect the result.",
  "المسافة وحجم الصورة": "Distance and image size",
  "راجع Throw Ratio والمسافة المطلوبة قبل الشراء، وقس الجدار ومكان الجهاز. وجود تصحيح keystone لا يعوض دائماً عن وضع غير مناسب وقد يقلل حدة الصورة.": "Check the throw ratio and required distance before buying, and measure the wall and projector position. Keystone correction cannot always compensate for poor placement and may reduce image sharpness.",
  "الصوت والاتصال": "Audio and connectivity",
  "افحص HDMI وARC أو مخرج الصوت والبلوتوث، وتأكد من توافق تطبيقات البث إن كان النظام ذكياً. للمشاهدة الجادة قد تحتاج سماعة خارجية حتى لو كان الجهاز يحتوي سماعات.": "Check HDMI, ARC or audio output, and Bluetooth. If it has a smart system, confirm streaming-app compatibility. For more demanding viewing, you may need an external speaker even if speakers are built in.",
  "كيف تقارن تلفزيونات TCL قبل الشراء؟": "How to compare TCL televisions before buying",
  "خطوات لفهم حجم الشاشة ونوع اللوحة والتحديث وميزات الألعاب في تلفزيونات TCL.": "Steps to understand screen size, panel type, refresh rate and gaming features on TCL TVs.",
  "الاسم التجاري وحده لا يكفي للمقارنة؛ سلسلة الموديل والسنة والمقاس قد تغير نوع اللوحة والسطوع وعدد المنافذ. ابدأ برقم الموديل الكامل كما يظهر لدى المتجر.": "A brand name alone is not enough for comparison. The series, year and size may change the panel, brightness and port count. Start with the full model number shown by the store.",
  "اختر المقاس حسب المسافة": "Choose a size for your viewing distance",
  "المقاس الأكبر ليس أفضل دائماً إذا كانت مسافة الجلوس قصيرة أو جودة المحتوى منخفضة. قس المسافة وحدد مكان الشاشة والحامل قبل اختيار المقاس.": "Bigger is not always better if you sit close or watch low-quality content. Measure the viewing distance and decide the screen and stand position before choosing a size.",
  "Mini-LED وQLED ليستا الشيء نفسه": "Mini-LED and QLED are not the same",
  "QLED تصف طبقة تحسين اللون، بينما Mini-LED تتعلق غالباً بإضاءة خلفية بعدد مناطق أكبر. افحص نوع اللوحة وعدد مناطق التعتيم والسطوع بدلاً من الاعتماد على الشعار فقط.": "QLED describes a colour-enhancement layer, while Mini-LED usually refers to a backlight with more zones. Check the panel type, dimming zones and brightness rather than relying on the badge alone.",
  "للاعبين": "For gamers",
  "راجع معدل التحديث الأصلي، HDMI 2.1، VRR وALLM، وعدد المنافذ التي تدعمها فعلياً. بعض المزايا قد تعمل بدقة أو معدل محدد فقط.": "Check the native refresh rate, HDMI 2.1, VRR, ALLM, and the number of ports that actually support them. Some features may work only at a particular resolution or refresh rate.",
  "النظام والضمان": "System and warranty",
  "اختر النظام الذي تتوفر عليه تطبيقاتك، وافحص سياسة التحديث والضمان المحلي. السعر والتوفر والمواصفات النهائية يجب تأكيدها في صفحة البائع قبل الدفع.": "Choose a system with the apps you use, and check its update policy and local warranty. Confirm final price, availability and specifications on the seller's page before paying.",
  "بداية عملية للمنزل الذكي دون تعقيد": "A practical, uncomplicated start to a smart home",
  "اختر منصة موحدة واتصالاً مناسباً وابدأ بأجهزة تحقق فائدة يومية واضحة.": "Choose a shared platform and suitable connectivity, then start with devices that offer clear everyday value.",
  "أفضل منزل ذكي ليس الأكثر أجهزة، بل الأقل احتياجاً للصيانة والأوضح فائدة. ابدأ بمشكلة واحدة مثل الإضاءة أو المراقبة أو التحكم بالطاقة، ثم وسّع النظام تدريجياً.": "The best smart home is not the one with the most devices, but the one needing the least maintenance and providing the clearest benefit. Start with one problem, such as lighting, monitoring or power control, then expand gradually.",
  "اختر المنصة أولاً": "Choose the platform first",
  "حدد إن كنت تعتمد Apple Home أو Google Home أو Alexa أو منصة أخرى، ثم تحقق من شعار التوافق على المنتج. معيار Matter قد يسهل الربط لكنه لا يضمن توفر كل المزايا على كل منصة.": "Decide whether you use Apple Home, Google Home, Alexa or another platform, then check the product's compatibility label. Matter can make connections easier but does not guarantee every feature on every platform.",
  "Wi‑Fi أم Zigbee أم Thread": "Wi-Fi, Zigbee or Thread",
  "أجهزة Wi‑Fi سهلة البدء لكنها تعتمد على الراوتر، بينما قد تحتاج Zigbee إلى محور. Thread مصمم لشبكة منخفضة الطاقة ويتطلب Border Router متوافقاً في بعض الحالات.": "Wi-Fi devices are easy to start with but depend on your router, while Zigbee may require a hub. Thread is designed for low-power networking and may require a compatible Border Router.",
  "الأمان والخصوصية": "Security and privacy",
  "غيّر كلمات المرور الافتراضية، فعّل التحديث التلقائي والمصادقة الثنائية للحسابات، وضع أجهزة إنترنت الأشياء على شبكة منفصلة إذا كان الراوتر يدعم ذلك.": "Change default passwords, enable automatic updates and two-factor authentication for accounts, and place connected devices on a separate network if your router supports it.",
  "ابدأ بما يوفر وقتاً": "Start with something that saves time",
  "مقبس ذكي لمهمة متكررة أو حساس تسرب أو إضاءة تلقائية قد يكون أكثر فائدة من جهاز معقد. راجع الجهد والقابس والتوافق قبل الشراء.": "A smart plug for a recurring task, a leak sensor or automatic lighting may be more useful than a complex device. Check voltage, plug type and compatibility before buying.",
  "قائمة فحص قبل شراء إكسسوارات السيارة": "A checklist before buying car accessories",
  "تأكد من التوافق والطاقة والتثبيت ودرجات الحرارة قبل طلب إكسسوارات السيارة.": "Check compatibility, power, mounting and temperature ratings before ordering car accessories.",
  "كثير من إكسسوارات السيارة تبدو عامة لكنها تعتمد على مقاس الفتحة أو نوع المنفذ أو تصميم لوحة القيادة. دقائق القياس قبل الطلب تقلل احتمال شراء منتج غير مناسب.": "Many car accessories look universal but depend on the opening size, port type or dashboard design. A few minutes of measuring before ordering can reduce the chance of buying an unsuitable product.",
  "التوافق الدقيق": "Exact compatibility",
  "لا تكتفِ باسم السيارة؛ السنة والفئة قد تغيران التصميم. راجع المقاسات ورقم القطعة وصور موضع التركيب، واسأل البائع إذا لم تكن المعلومات واضحة.": "Do not rely only on the car's name: year and trim can change the design. Check measurements, part numbers and installation-location photos, and ask the seller if the information is unclear.",
  "الحرارة والطاقة": "Heat and power",
  "مقصورة السيارة قد تصل إلى درجات حرارة مرتفعة. افحص مجال حرارة التشغيل، ونوع مصدر الطاقة، وقدرة منفذ USB أو ولاعة السيارة قبل تركيب كاميرا أو شاحن.": "The car cabin can reach high temperatures. Check the operating-temperature range, power source, and USB or accessory-socket capacity before installing a camera or charger.",
  "تثبيت آمن": "Safe installation",
  "تجنب أي ملحق يحجب الرؤية أو الوسائد الهوائية أو أدوات التحكم. استخدم تثبيتاً مناسباً ولا تترك كابلات تعيق الدواسات أو الحركة.": "Avoid accessories that obstruct your view, airbags or controls. Use an appropriate mount and do not leave cables that interfere with pedals or movement.",
  "راجع سياسة الإرجاع": "Check the returns policy",
  "المنتجات التي تعتمد على المقاس أكثر عرضة لعدم الملاءمة؛ راجع الإرجاع والشحن إلى السعودية والسعر النهائي في صفحة المتجر قبل إكمال الطلب.": "Size-dependent products are more likely not to fit. Check returns, shipping to Saudi Arabia and the final store price before completing your order."
};
