function escapeHtml(value) {
  return String(value || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export function adminPage({ nonce, email, siteUrl }) {
  const safeEmail = escapeHtml(email);
  const safeSiteUrl = escapeHtml(siteUrl);
  return `<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow,noarchive">
  <title>لوحة إدارة أوفرلي</title>
  <style nonce="${nonce}">
    :root{color-scheme:dark;--bg:#050909;--panel:#0b1514;--panel2:#10201e;--line:rgba(132,224,214,.16);--text:#f4fbfa;--muted:#9fb4b1;--accent:#86d6ce;--danger:#ff7e8f;--ok:#66d7a8;--shadow:0 28px 80px rgba(0,0,0,.34)}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 80% -10%,rgba(74,162,153,.22),transparent 32rem),var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","SF Arabic",Tahoma,sans-serif;line-height:1.55}
    button,input,select{font:inherit}button{cursor:pointer}.shell{width:min(1180px,calc(100% - 28px));margin:auto}.header{position:sticky;top:0;z-index:20;border-bottom:1px solid var(--line);background:rgba(5,9,9,.86);backdrop-filter:blur(20px)}
    .nav{min-height:74px;display:flex;align-items:center;justify-content:space-between;gap:16px}.brand{display:flex;align-items:center;gap:12px;font-weight:900}.mark{display:grid;place-items:center;width:42px;height:42px;border:1px solid var(--line);border-radius:14px;background:linear-gradient(145deg,#17322f,#091211);color:var(--accent)}
    .nav-actions{display:flex;align-items:center;gap:10px}.email{max-width:260px;overflow:hidden;text-overflow:ellipsis;color:var(--muted);font-size:12px;direction:ltr}.site-link,.ghost{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 14px;border:1px solid var(--line);border-radius:999px;color:var(--text);background:rgba(255,255,255,.03);text-decoration:none;font-weight:700}
    main{padding:44px 0 80px}.hero{display:grid;grid-template-columns:1.2fr .8fr;gap:20px;align-items:end;margin-bottom:22px}.hero h1{margin:0;font-size:clamp(34px,6vw,68px);line-height:1;letter-spacing:-.05em}.hero p{max-width:670px;margin:18px 0 0;color:var(--muted)}
    .stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stat{padding:18px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,var(--panel2),var(--panel));box-shadow:var(--shadow)}.stat span{display:block;color:var(--muted);font-size:11px}.stat strong{display:block;margin-top:5px;font-size:23px}
    .grid{display:grid;grid-template-columns:390px 1fr;gap:18px;align-items:start}.panel{border:1px solid var(--line);border-radius:26px;background:linear-gradient(145deg,rgba(16,32,30,.98),rgba(8,16,15,.98));box-shadow:var(--shadow);overflow:hidden}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:20px 22px;border-bottom:1px solid var(--line)}.panel-head h2{margin:0;font-size:18px}.panel-body{padding:20px}
    .form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:grid;gap:7px}.field.full{grid-column:1/-1}.field label{color:var(--muted);font-size:12px;font-weight:700}.input{width:100%;min-height:45px;padding:10px 12px;border:1px solid var(--line);border-radius:13px;outline:none;color:var(--text);background:#07100f}.input:focus{border-color:rgba(134,214,206,.58);box-shadow:0 0 0 3px rgba(134,214,206,.08)}
    .primary{width:100%;min-height:50px;margin-top:16px;border:0;border-radius:15px;color:#04100e;background:linear-gradient(135deg,#a8ebe5,#69beb6);font-weight:900}.primary:disabled,.danger:disabled{opacity:.5;cursor:not-allowed}.hint{margin:12px 0 0;color:var(--muted);font-size:11px}.status{min-height:22px;margin-top:12px;font-size:12px}.status.ok{color:var(--ok)}.status.error{color:var(--danger)}
    .toolbar{display:flex;gap:10px;padding:16px 20px;border-bottom:1px solid var(--line)}.toolbar .input{flex:1}.toolbar button{min-width:86px;border:1px solid var(--line);border-radius:13px;color:var(--text);background:var(--panel2);font-weight:800}.products{display:grid}.product{display:grid;grid-template-columns:64px minmax(0,1fr) auto;gap:14px;align-items:center;padding:14px 20px;border-bottom:1px solid var(--line)}.product:last-child{border-bottom:0}.product img{width:64px;height:64px;object-fit:contain;border-radius:14px;background:#fff}.product h3{margin:0;font-size:14px;line-height:1.45}.meta{display:flex;flex-wrap:wrap;gap:6px 12px;margin-top:7px;color:var(--muted);font-size:11px}.actions{display:grid;gap:7px}.actions button{min-width:62px;min-height:34px;border:1px solid var(--line);border-radius:10px;color:var(--text);background:transparent;font-size:11px;font-weight:800}.actions .danger{color:var(--danger);border-color:rgba(255,126,143,.24)}
    .pager{display:flex;align-items:center;justify-content:center;gap:12px;padding:18px;border-top:1px solid var(--line)}.pager button{min-width:80px;min-height:38px;border:1px solid var(--line);border-radius:12px;color:var(--text);background:var(--panel2)}.pager span{color:var(--muted);font-size:12px}.empty{padding:54px 20px;text-align:center;color:var(--muted)}
    .security-note{margin-top:18px;padding:16px 18px;border:1px solid rgba(102,215,168,.18);border-radius:18px;background:rgba(102,215,168,.05);color:#b8d5d1;font-size:12px}
    .analytics{margin-bottom:18px}.analytics-head{align-items:center}.analytics-tools{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.range-btn{min-height:34px;padding:0 11px;border:1px solid var(--line);border-radius:999px;color:var(--muted);background:transparent;font-size:11px;font-weight:800}.range-btn.active{color:#04100e;border-color:transparent;background:var(--accent)}.analytics-body{padding:20px}.metric-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.metric{padding:17px;border:1px solid var(--line);border-radius:18px;background:rgba(255,255,255,.025)}.metric span{display:block;color:var(--muted);font-size:11px}.metric strong{display:block;margin-top:4px;font-size:25px}.metric small{display:block;margin-top:3px;color:#71938e;font-size:10px}.analytics-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:12px;margin-top:12px}.analytics-card{min-width:0;padding:18px;border:1px solid var(--line);border-radius:20px;background:#07100f}.analytics-card h3{margin:0 0 14px;font-size:14px}.analytics-card.wide{grid-column:1/-1}.legend{display:flex;gap:14px;margin:-5px 0 12px;color:var(--muted);font-size:10px}.legend i{display:inline-block;width:8px;height:8px;margin-left:5px;border-radius:50%;background:var(--accent)}.legend i.click{background:#f4b96f}.chart-scroll{overflow-x:auto;padding-bottom:5px}.daily-chart{display:flex;align-items:end;gap:6px;min-height:210px}.day-column{display:grid;grid-template-rows:170px 20px;align-items:end;justify-items:center;min-width:18px;flex:1}.day-bars{height:170px;display:flex;align-items:end;gap:2px}.day-bar{display:block;width:6px;min-height:2px;border-radius:6px 6px 2px 2px;background:linear-gradient(#a8ebe5,#54a9a1)}.day-bar.clicks{background:linear-gradient(#ffd59d,#e59135)}.day-label{direction:ltr;color:#66817d;font-size:8px;white-space:nowrap}.rank-list,.break-list{display:grid;gap:11px}.rank-item{display:grid;gap:7px}.rank-line{display:flex;align-items:center;justify-content:space-between;gap:12px}.rank-title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#dcebea;font-size:11px}.rank-value{flex:0 0 auto;color:var(--accent);font-size:11px;font-weight:900}.track{height:5px;overflow:hidden;border-radius:99px;background:rgba(255,255,255,.06)}.track span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#58aca4,#a8ebe5)}.breakdowns{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:12px}.break-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px;align-items:center}.break-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#bcd0cd;font-size:11px}.break-count{color:var(--accent);font-size:11px;font-weight:900}.analytics-empty{padding:38px 12px;text-align:center;color:var(--muted);font-size:12px}.analytics-updated{color:#6e8d89;font-size:10px}
    @media(max-width:900px){.hero,.grid,.analytics-grid{grid-template-columns:1fr}.stats{margin-top:12px}.metric-grid{grid-template-columns:repeat(3,1fr)}.breakdowns{grid-template-columns:1fr 1fr}.analytics-card.wide{grid-column:auto}}@media(max-width:620px){.email{display:none}.site-link{padding:0 10px;font-size:12px}.stats,.metric-grid{grid-template-columns:1fr 1fr}.stat:last-child,.metric:last-child{grid-column:1/-1}.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.product{grid-template-columns:54px 1fr}.product img{width:54px;height:54px}.actions{grid-column:1/-1;grid-template-columns:1fr 1fr}.toolbar{flex-wrap:wrap}.toolbar .input{flex-basis:100%}.breakdowns{grid-template-columns:1fr}.analytics-body{padding:14px}.analytics-tools{width:100%}.analytics-head{align-items:flex-start;flex-direction:column}}
  </style>
</head>
<body>
  <header class="header"><div class="shell nav"><div class="brand"><span class="mark">ع</span><span>إدارة أوفرلي</span></div><div class="nav-actions"><span class="email">${safeEmail}</span><a class="site-link" href="${safeSiteUrl}" target="_blank" rel="noopener">عرض الموقع ↗</a></div></div></header>
  <main class="shell">
    <section class="hero"><div><h1>منتجاتك تحت السيطرة.</h1><p>أضف المنتجات اليدوية، راجع القائمة، وعدّل أو احذف من مكان واحد. الحفظ يتم عبر الخادم الآمن ولا تصل مفاتيح GitHub إلى هذه الصفحة.</p></div><div class="stats"><div class="stat"><span>إجمالي المنتجات</span><strong id="totalCount">—</strong></div><div class="stat"><span>Amazon</span><strong id="amazonCount">—</strong></div><div class="stat"><span>AliExpress</span><strong id="aliCount">—</strong></div></div></section>
    <section class="panel analytics">
      <div class="panel-head analytics-head"><div><h2>لوحة الأداء</h2><span class="analytics-updated" id="analyticsUpdated">بيانات مجمعة تحافظ على الخصوصية</span></div><div class="analytics-tools"><button class="range-btn" type="button" data-days="7">7 أيام</button><button class="range-btn active" type="button" data-days="30">30 يومًا</button><button class="range-btn" type="button" data-days="90">90 يومًا</button><button class="ghost" id="refreshAnalytics" type="button">تحديث</button></div></div>
      <div class="analytics-body">
        <div class="metric-grid"><div class="metric"><span>زيارات الموقع</span><strong id="metricViews">—</strong><small>مشاهدات الصفحات</small></div><div class="metric"><span>نقرات المنتجات</span><strong id="metricClicks">—</strong><small>انتقال للمتاجر</small></div><div class="metric"><span>معدل النقر CTR</span><strong id="metricCtr">—</strong><small>النقرات ÷ الزيارات</small></div><div class="metric"><span>زيارات اليوم</span><strong id="metricViewsToday">—</strong><small>منذ بداية اليوم</small></div><div class="metric"><span>نقرات اليوم</span><strong id="metricClicksToday">—</strong><small>اهتمام لحظي</small></div></div>
        <div class="analytics-grid"><article class="analytics-card wide"><h3>النشاط اليومي</h3><div class="legend"><span><i></i>الزيارات</span><span><i class="click"></i>النقرات</span></div><div class="chart-scroll"><div class="daily-chart" id="dailyChart"><div class="analytics-empty">جاري تحميل التحليلات…</div></div></div></article><article class="analytics-card"><h3>المنتجات الأكثر نقرًا</h3><div class="rank-list" id="topProducts"></div></article><article class="analytics-card"><h3>ملخص الاهتمام</h3><div class="rank-list" id="interestSummary"></div></article></div>
        <div class="breakdowns"><article class="analytics-card"><h3>التصنيفات</h3><div class="break-list" id="categoriesBreakdown"></div></article><article class="analytics-card"><h3>المتاجر</h3><div class="break-list" id="storesBreakdown"></div></article><article class="analytics-card"><h3>الأجهزة</h3><div class="break-list" id="devicesBreakdown"></div></article><article class="analytics-card"><h3>الدول</h3><div class="break-list" id="countriesBreakdown"></div></article><article class="analytics-card"><h3>مصادر الزيارة</h3><div class="break-list" id="referrersBreakdown"></div></article></div>
      </div>
    </section>
    <section class="grid">
      <article class="panel"><div class="panel-head"><h2 id="formTitle">إضافة منتج يدوي</h2><button class="ghost" id="resetForm" type="button">جديد</button></div><div class="panel-body">
        <form id="productForm" autocomplete="off">
          <input type="hidden" id="editingKey">
          <div class="form-grid">
            <div class="field"><label for="store">المتجر</label><select class="input" id="store" required><option value="amazon">Amazon السعودية</option><option value="aliexpress">AliExpress</option></select></div>
            <div class="field"><label for="identifier" id="identifierLabel">ASIN</label><input class="input" id="identifier" dir="ltr" maxlength="20" required placeholder="B0XXXXXXXX"></div>
            <div class="field full"><label for="title">اسم المنتج</label><input class="input" id="title" maxlength="180" required></div>
            <div class="field full"><label for="image">رابط الصورة HTTPS</label><input class="input" id="image" dir="ltr" type="url" required></div>
            <div class="field full" id="urlField"><label for="url">رابط عمولة AliExpress</label><input class="input" id="url" dir="ltr" type="url"></div>
            <div class="field"><label for="price">السعر قبل الخصم (ر.س)</label><input class="input" id="price" type="number" min="0.01" max="100000" step="0.01" required></div>
            <div class="field"><label for="discount">نسبة الخصم %</label><input class="input" id="discount" type="number" min="0" max="95" value="0" required></div>
            <div class="field"><label for="sales">عدد المبيعات (اختياري)</label><input class="input" id="sales" type="number" min="0" step="1"></div>
            <div class="field"><label for="rating">التقييم % (اختياري)</label><input class="input" id="rating" type="number" min="0" max="100" step="0.1"></div>
            <div class="field full"><label for="category">التصنيف</label><select class="input" id="category" required><option>الإلكترونيات</option><option>التنظيف والمنظفات</option><option>الأزياء والأحذية</option><option>المطبخ والأجهزة المنزلية</option><option>الأثاث والديكور</option><option>المنزل</option><option>السيارة</option><option>السفر</option><option>الرحلات والبحر والتخييم</option><option>الحدائق والزراعة</option><option>الجمال والعناية</option><option>الصحة والعناية</option><option>البقالة والمشروبات</option><option>الرياضة</option><option>الأطفال</option><option>الألعاب</option><option>الحيوانات الأليفة</option><option>الأدوات والهوايات</option><option>الترفيه المنزلي</option><option>المدرسة والقرطاسية</option><option>الكتب والمكتب</option><option>الساعات والمجوهرات</option><option>تسوق متنوع</option></select></div>
          </div>
          <button class="primary" id="saveButton" type="submit">حفظ ونشر المنتج</button><div class="status" id="formStatus" role="status"></div>
        </form>
        <p class="hint">المنتج اليدوي يُعلّم كاختيار للمالك حتى لا يحذفه التحديث الآلي. لا تضع أي مفتاح أو كلمة مرور في الحقول.</p>
      </div></article>
      <article class="panel"><div class="panel-head"><h2>المنتجات المنشورة</h2><button class="ghost" id="refresh" type="button">تحديث</button></div><div class="toolbar"><input class="input" id="search" placeholder="ابحث بالاسم أو الرقم"><button id="searchButton" type="button">بحث</button></div><div class="products" id="products"><div class="empty">جاري تحميل المنتجات…</div></div><div class="pager"><button id="prevPage" type="button">السابق</button><span id="pageLabel">—</span><button id="nextPage" type="button">التالي</button></div></article>
    </section>
    <div class="security-note">🔒 الدخول محمي بواسطة Cloudflare Access، والهوية تُفحص مرة ثانية داخل الخادم. جميع عمليات الحفظ تُسجّل كتعديلات في GitHub ويمكن الرجوع عنها.</div>
  </main>
  <script nonce="${nonce}">
    const state={page:1,pages:1,query:"",items:[],analyticsDays:30};
    const $=id=>document.getElementById(id);
    const setStatus=(message,type="")=>{$("formStatus").textContent=message;$("formStatus").className=("status "+type).trim()};
    const keyOf=item=>item.store==="aliexpress"?"aliexpress:"+item.product_id:"amazon:"+item.asin;
    const number=value=>new Intl.NumberFormat("ar-SA").format(Number(value||0));
    const percent=value=>new Intl.NumberFormat("ar-SA",{maximumFractionDigits:1}).format(Number(value||0))+"٪";
    const labelMap={amazon:"Amazon",aliexpress:"AliExpress",mobile:"جوال",tablet:"جهاز لوحي",desktop:"كمبيوتر",direct:"دخول مباشر",SA:"السعودية"};
    function syncStore(){const ali=$("store").value==="aliexpress";$("identifierLabel").textContent=ali?"رقم منتج AliExpress":"ASIN";$("identifier").placeholder=ali?"1005000000000000":"B0XXXXXXXX";$("urlField").hidden=!ali;$("url").required=ali}
    function resetForm(){$("productForm").reset();$("editingKey").value="";$("discount").value="0";$("formTitle").textContent="إضافة منتج يدوي";$("saveButton").textContent="حفظ ونشر المنتج";setStatus("");syncStore()}
    function productPayload(){const store=$("store").value;return{store,[store==="aliexpress"?"product_id":"asin"]:$("identifier").value.trim(),title:$("title").value.trim(),image:$("image").value.trim(),url:$("url").value.trim(),original_price:Number($("price").value),discount_percent:Number($("discount").value),sales_volume:Number($("sales").value||0),rating:Number($("rating").value||0),category:$("category").value}}
    async function api(path,options={}){const response=await fetch(path,{...options,headers:{"Accept":"application/json","Content-Type":"application/json","X-Overly-Admin":"1",...(options.headers||{})},cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"تعذر تنفيذ الطلب");return payload}
    function renderItems(){const box=$("products");box.textContent="";if(!state.items.length){const empty=document.createElement("div");empty.className="empty";empty.textContent="لا توجد منتجات مطابقة";box.append(empty);return}state.items.forEach(item=>{const row=document.createElement("div");row.className="product";const img=document.createElement("img");img.src=item.image;img.alt="";img.loading="lazy";const info=document.createElement("div");const title=document.createElement("h3");title.textContent=item.title;const meta=document.createElement("div");meta.className="meta";[item.store==="aliexpress"?"AliExpress":"Amazon",item.category,number(item.original_price)+" ر.س",item.discount_percent>0?"خصم "+number(item.discount_percent)+"٪":"رائج",item.sales_volume?number(item.sales_volume)+" مبيعة":""].filter(Boolean).forEach(text=>{const span=document.createElement("span");span.textContent=text;meta.append(span)});info.append(title,meta);const actions=document.createElement("div");actions.className="actions";const edit=document.createElement("button");edit.type="button";edit.textContent="تعديل";edit.addEventListener("click",()=>editItem(item));const del=document.createElement("button");del.type="button";del.className="danger";del.textContent="حذف";del.addEventListener("click",()=>deleteItem(item,del));actions.append(edit,del);row.append(img,info,actions);box.append(row)})}
    function editItem(item){$("editingKey").value=keyOf(item);$("store").value=item.store||"amazon";syncStore();$("identifier").value=item.store==="aliexpress"?item.product_id:item.asin;$("title").value=item.title||"";$("image").value=item.image||"";$("url").value=item.url||"";$("price").value=item.original_price||"";$("discount").value=item.discount_percent||0;$("sales").value=item.sales_volume||"";$("rating").value=item.rating||"";$("category").value=item.category||"الإلكترونيات";$("formTitle").textContent="تعديل المنتج";$("saveButton").textContent="حفظ التعديلات";scrollTo({top:0,behavior:"smooth"})}
    async function load(){const params=new URLSearchParams({page:String(state.page),page_size:"40"});if(state.query)params.set("q",state.query);$("products").innerHTML='<div class="empty">جاري تحميل المنتجات…</div>';try{const data=await api("/api/products?"+params);state.items=data.products;state.pages=data.pages;state.page=data.page;$("totalCount").textContent=number(data.stats.total);$("amazonCount").textContent=number(data.stats.amazon);$("aliCount").textContent=number(data.stats.aliexpress);$("pageLabel").textContent="صفحة "+number(data.page)+" من "+number(data.pages);$("prevPage").disabled=data.page<=1;$("nextPage").disabled=data.page>=data.pages;renderItems()}catch(error){const empty=document.createElement("div");empty.className="empty";empty.textContent=error.message;$("products").textContent="";$("products").append(empty)}}
    async function deleteItem(item,button){if(!confirm("حذف «"+item.title+"» من الموقع؟"))return;button.disabled=true;try{await api("/api/products/"+encodeURIComponent(keyOf(item)),{method:"DELETE",body:"{}"});await load()}catch(error){alert(error.message);button.disabled=false}}
    function renderRanked(id,items,labelField="title",valueField="clicks"){const box=$(id);box.textContent="";if(!items.length){const empty=document.createElement("div");empty.className="analytics-empty";empty.textContent="لا توجد بيانات بعد";box.append(empty);return}const max=Math.max(...items.map(item=>Number(item[valueField]||0)),1);items.forEach(item=>{const row=document.createElement("div");row.className="rank-item";const line=document.createElement("div");line.className="rank-line";const title=document.createElement("span");title.className="rank-title";title.textContent=labelMap[item[labelField]]||item[labelField]||"غير محدد";const value=document.createElement("strong");value.className="rank-value";value.textContent=number(item[valueField]);const track=document.createElement("div");track.className="track";const fill=document.createElement("span");fill.style.width=Math.max(3,Number(item[valueField]||0)/max*100)+"%";track.append(fill);line.append(title,value);row.append(line,track);box.append(row)})}
    function renderBreakdown(id,items){const box=$(id);box.textContent="";if(!items.length){const empty=document.createElement("div");empty.className="analytics-empty";empty.textContent="لا توجد بيانات";box.append(empty);return}items.forEach(item=>{const row=document.createElement("div");row.className="break-item";const name=document.createElement("span");name.className="break-name";name.textContent=labelMap[item.label]||item.label||"غير محدد";const count=document.createElement("strong");count.className="break-count";count.textContent=number(item.count);row.append(name,count);box.append(row)})}
    function renderDaily(items){const box=$("dailyChart");box.textContent="";if(!items.length){const empty=document.createElement("div");empty.className="analytics-empty";empty.textContent="ستظهر الحركة هنا بعد بدء تسجيل الزيارات";box.append(empty);return}box.style.minWidth=Math.max(560,items.length*22)+"px";const max=Math.max(...items.flatMap(item=>[Number(item.views||0),Number(item.clicks||0)]),1);items.forEach((item,index)=>{const column=document.createElement("div");column.className="day-column";const bars=document.createElement("div");bars.className="day-bars";const views=document.createElement("span");views.className="day-bar";views.style.height=Math.max(2,Number(item.views||0)/max*165)+"px";views.title=number(item.views)+" زيارة";const clicks=document.createElement("span");clicks.className="day-bar clicks";clicks.style.height=Math.max(2,Number(item.clicks||0)/max*165)+"px";clicks.title=number(item.clicks)+" نقرة";const label=document.createElement("span");label.className="day-label";label.textContent=(items.length<=14||index%Math.ceil(items.length/12)===0)?String(item.day||"").slice(5):"";bars.append(views,clicks);column.append(bars,label);box.append(column)})}
    async function loadAnalytics(){const refresh=$("refreshAnalytics");refresh.disabled=true;document.querySelectorAll(".range-btn").forEach(button=>button.classList.toggle("active",Number(button.dataset.days)===state.analyticsDays));try{const data=await api("/api/analytics?days="+state.analyticsDays);$("metricViews").textContent=number(data.summary.views);$("metricClicks").textContent=number(data.summary.clicks);$("metricCtr").textContent=percent(data.summary.ctr);$("metricViewsToday").textContent=number(data.summary.views_today);$("metricClicksToday").textContent=number(data.summary.clicks_today);$("analyticsUpdated").textContent="آخر تحديث "+new Date(data.generated_at).toLocaleString("ar-SA");renderDaily(data.daily);renderRanked("topProducts",data.top_products);renderRanked("interestSummary",[...data.categories.slice(0,3),...data.stores.slice(0,2)],"label","count");renderBreakdown("categoriesBreakdown",data.categories);renderBreakdown("storesBreakdown",data.stores);renderBreakdown("devicesBreakdown",data.devices);renderBreakdown("countriesBreakdown",data.countries);renderBreakdown("referrersBreakdown",data.referrers)}catch(error){$("analyticsUpdated").textContent=error.message;["dailyChart","topProducts","interestSummary","categoriesBreakdown","storesBreakdown","devicesBreakdown","countriesBreakdown","referrersBreakdown"].forEach(id=>{const box=$(id);box.textContent="";const empty=document.createElement("div");empty.className="analytics-empty";empty.textContent="التحليلات غير متاحة بعد";box.append(empty)})}finally{refresh.disabled=false}}
    $("productForm").addEventListener("submit",async event=>{event.preventDefault();const button=$("saveButton");button.disabled=true;setStatus("جاري الحفظ الآمن…");try{await api("/api/products",{method:"POST",body:JSON.stringify({product:productPayload(),previous_key:$("editingKey").value})});setStatus("تم الحفظ والنشر بنجاح.","ok");resetForm();await load()}catch(error){setStatus(error.message,"error")}finally{button.disabled=false}});
    $("store").addEventListener("change",syncStore);$("resetForm").addEventListener("click",resetForm);$("refresh").addEventListener("click",load);$("refreshAnalytics").addEventListener("click",loadAnalytics);document.querySelectorAll(".range-btn").forEach(button=>button.addEventListener("click",()=>{state.analyticsDays=Number(button.dataset.days);loadAnalytics()}));$("searchButton").addEventListener("click",()=>{state.query=$("search").value.trim();state.page=1;load()});$("search").addEventListener("keydown",event=>{if(event.key==="Enter")$("searchButton").click()});$("prevPage").addEventListener("click",()=>{if(state.page>1){state.page--;load()}});$("nextPage").addEventListener("click",()=>{if(state.page<state.pages){state.page++;load()}});
    syncStore();load();loadAnalytics();
  </script>
</body>
</html>`;
}
